version: "3.4"

networks:
  production-network:
    driver:
      bridge

services:
  mongodb:
    image: mongo:latest
    restart: always
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    container_name: mongo-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - production-network

  springboot-app:
    depends_on:
      mongodb:
        condition: service_healthy
    image: springboot-app
    container_name: spring
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:123456@localhost:27017/fourd?authSource=admin
    networks:
      - production-network
