server:
  port: 8080

spring:
  data:
    mongodb:
      uri: "mongodb://admin:123456@localhost:27017/fourd?authSource=admin"

jwt:
  secret: ec48c3300ab911eebe560242ac120002a16sda5sd1as5d1a9d1as9d1asdaas1da1sdas1da6sd1a8sd7A8ds1as1d6as1d9a1